libafs: Redfine free_sock_hash_table[] on AIX + Open XL C
On AIX, when using the CLANG-based Open XL C 17.1.0+
compiler, during the kernel extension build, we include the
system header sys/socketvar.h.  Unfortunately this file
contains the following statement:

extern struct free_sock_hash_bucket free_sock_hash_table[];

This statement causes the following compiler error when
building src/external/heimdal/hcrypto/sha256.c (and others):

In file included from /home/build/openafs/src/external/heimdal/hcrypto/sha256.c:34:
In file included from /home/build/openafs/src/crypto/hcrypto/kernel/config.h:30:
In file included from /home/build/openafs/src/afs/sysincludes.h:276:
../sys/socketvar.h:158:57: error: array has incomplete element type 'struct free_sock_hash_bucket'
extern struct free_sock_hash_bucket free_sock_hash_table[];
                                                        ^
../sys/socketvar.h:158:15: note: forward declaration of 'struct free_sock_hash_bucket'
extern struct free_sock_hash_bucket free_sock_hash_table[];
              ^

As this is an IBM-supplied header, we cannot change it.
Since we don't actually need free_sock_hash_table,
redefine it to something harmless that will compile.
Unfortuntely, sys/socketvar.h is included in a number of
different places, several of which don't have many earlier
includes in common, and the redefinition is needed before
sys/socketvar.h is included.  Therefore, perform the
redefine in the platform-specific src/config/
param.rs_aix72.h and param.rs_aix73.h headers.

Change-Id: Ia60f59bb724f2d66e315db374f790c473886320d