export: Don't use compiler built-ins for kernel functions
When building the export extension using the Open XL C 17.1+
compilers, the link step fails with the following error:

        if [ "xyes" = "xyes" ]; then   /usr/bin/ld -b64 -o export64.ext -eexport /lib/kernex.exp /lib/syscalls.exp ./extras.exp export64.o symtab64.o  -bexport:export64.exp -lcsys ;  fi
ld: 0711-224 WARNING: Duplicate symbol: .___strcmp64
ld: 0711-224 WARNING: Duplicate symbol: ___strcmp64
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
ld: 0711-317 ERROR: Undefined symbol: .puts
make: The error code from the last command is 8.

This is because the compiler uses it's own implementation
of strcmp, which internally uses puts.  These functions
are not available in the AIX kernel.  Instead, use the CLANG
-fno-builtin argument to force the use of the AIX-supplied
function.

Change-Id: I537d06791ef731953fca80e5eb7181e7cbf79d4c