rx: Use variadic osi_Panic on AIX + Open XL C
When compiling the kernel extension on AIX 7.2+ using
the CLANG-based Open XL C 17.1+, calls to osi_Panic
generate the following compiler error:

In file included from /home/build/openafs/src/external/heimdal/hcrypto/sha256.c:34:
/home/build/openafs/src/crypto/hcrypto/kernel/config.h:101:75: error: too few arguments to function call, expected 4, have 1
static_inline void _afscrypto_abort(void) {osi_Panic("hckernel aborting\n");}
                                           ~~~~~~~~~                      ^
/home/build/openafs/src/rx/rx_kernel.h:50:13: note: 'osi_Panic' declared here
extern void osi_Panic(char *fmt, void *a1, void *a2, void *a3);
            ^

Unlike the older XL C 16.1 and earlier, the new 17.1+
can leverage the variadic osi_Panic implementation
currently used by Linux, etc.  However, this function
uses the vsnprintf.  This is unsuitable for the AIX
kernel extension.  Roken provides an implementation of
vsnprintf but this implementation requires the function
isdigit, which is not available in the AIX kernel either
and no suitable replacement is available.  Therefore we
avoid the call to vsnprintf and instead fall back on
plain printf.

Change-Id: I292b2f3b275eef52502000c6b214b2bcb2ee459d