AIX: Update function signatures to match system headers
When compiling the kernel extension on AIX 7.2+ using the
CLANG-based Open XL C 17.1+ compiler, numerous errors are
thrown due to functions being declared as static, while
the system headers define them as int.  The errors look
similar to this:

/home/build/openafs/src/afs/AIX/osi_vfsops.c:235:1: error: static declaration of 'afs_badop' follows non-static declaration
afs_badop()
^
/home/build/openafs/src/afs/afs_prototypes.h:987:12: note: previous declaration is here
extern int afs_badop(void);
           ^

Update the signatures to match the previous declarations.

Change-Id: I9eb2a4ab025c547c99db627b184e8f7d4c3e7e63