AIX: Call function with correct number of arguments
The function afs_fid is prototyped in src/afs/afs_prototypes.h.
In the AIX-specific prototype, it is declared as:

int afs_fid(OSI_VC_DECL(avc), struct fid *fidpp, struct ucred *credp);

However, in the AIX-specific module src/afs/AIX/osi_vnodeops.c,
in function afs_gn_fid, afs_fid is called with only two
arguments.  This causes the following compiler error when
using Open XL C 17.1+ on AIX 7.2+:

/home/build/openafs/src/afs/AIX/osi_vnodeops.c:226:29: error: too few arguments to function call, expected 3, have 2
    error = afs_fid(vp, fidp);
            ~~~~~~~         ^
/home/build/openafs/src/afs/afs_prototypes.h:1186:5: note: 'afs_fid' declared here
int afs_fid(OSI_VC_DECL(avc), struct fid *fidpp, struct ucred *credp);
    ^

Update the call to pass a NULL in place of the unused parameter.

Change-Id: I78cdb733def9ee0bacdf9650a77b5f970bb5509a