rx: Update function signatures for AIX
When compiling the kernel extension on AIX 7.2+
using the CLANG-based Open XL C 17.1+ compiler,
the build of src/rx/AIX/rx_knet.c throws two
errors due to two of the functions not having
a declared type:

/home/build/openafs/src/rx/AIX/rx_knet.c:167:6: error: non-void function 'rxk_RX_input' should return a value [-Wreturn-type]
            return;
            ^
...
/home/build/openafs/src/rx/AIX/rx_knet.c:239:6: error: non-void function 'rxk_isr' should return a value [-Wreturn-type]
            return;
            ^

Update the function signatures to void.

Change-Id: I436697e749d91f7586e1c299d4b39a84c2031684